apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-clock
spec:
  selector:
      matchLabels:
        app: react-clock
  replicas: 3
  template:
      metadata:
        labels:
            app: react-clock
      spec:
        containers:
        - name: react-clock
          image: boyercontainerregistry.azurecr.io/react-clock:v1
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8080
              path: /
          livenessProbe:
            httpGet:
              port: 8080
              path: /
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
